// Copyright (c) Dmitrii Erusov
// SPDX-License-Identifier: MPL-2.0

using Veriqa.Core.Configuration;

namespace Veriqa.Core.ChannelAdapter.UI;

/// <summary>
/// A custom resource of a page generated by the core together with its integrity pin — the pair
/// "path + SRI hash" (SPEC-012 §4.3, CFG-035). The pair is ONE setting rather than two, and it is carried in one value
/// on purpose: an SRI hash belongs to the file it was computed from, so a hash arriving from a level
/// other than the one that stated the path would make the browser reject the resource and the page
/// would silently lose its stylesheet or script. One value makes that split impossible — precedence
/// picks a whole pair (CFG-210), never one half of it.
/// </summary>
/// <param name="Path">Path or URL of the resource; never empty (an empty path states nothing).</param>
/// <param name="SriHash">SRI hash of the resource; null — the owning level pinned nothing.</param>
public sealed record CorePageCustomResource(string Path, string? SriHash)
{
    /// <summary>
    /// Builds the pair out of the two raw fields of a level's record, or <c>null</c> when the level
    /// states no resource. A blank value of either field means "not stated" — the same feature
    /// detection the page renderer performs over the resolved design.
    /// </summary>
    /// <param name="path">Raw path field of the level.</param>
    /// <param name="sriHash">Raw SRI hash field of the level.</param>
    /// <returns>The pair, or null when the level states no path.</returns>
    public static CorePageCustomResource? From(string? path, string? sriHash) =>
        string.IsNullOrWhiteSpace(path)
            ? null
            : new CorePageCustomResource(path, string.IsNullOrWhiteSpace(sriHash) ? null : sriHash);

    /// <summary>
    /// Builds the layer value of a level over its record: a level that states no path leaves the
    /// level UNSET, so precedence drops through to the level below and carries away that level's hash
    /// together with its path. A lone hash pins nothing and is deliberately not a value of its own.
    /// </summary>
    /// <param name="path">Raw path field of the level.</param>
    /// <param name="sriHash">Raw SRI hash field of the level.</param>
    /// <returns>Layer value of the level.</returns>
    public static LayerValue<CorePageCustomResource?> LayerOf(string? path, string? sriHash) =>
        From(path, sriHash) is { } resource
            ? LayerValue<CorePageCustomResource?>.Set(resource)
            : LayerValue<CorePageCustomResource?>.None;
}
