// Copyright (c) Dmitrii Erusov
// SPDX-License-Identifier: MPL-2.0

using Veriqa.Core.Configuration;

namespace Veriqa.Core.ChannelAdapter.UI;

/// <summary>
/// Registry of the canonical resolver keys that brand a page generated by the core (SPEC-012 §4.2–4.3,
/// §9, SPEC-007 UI-101): the preset, the brand primary color and the integrator's stylesheet.
/// <para>
/// The keys are declared HERE rather than in the AuthServer because their consumers live here: the
/// service pages of the contour (the email adapter surfaces, the render points behind
/// <see cref="CorePageHead"/>) — and ChannelAdapter cannot reference AuthServer, a reverse
/// dependency. They belong to ONE owner with the sign-in window keys of the auth server — the design
/// of the page — and that owner is spread over the two assemblies; the address of every level of
/// every key of it is stated in the declaration itself, and the records those addresses are read from
/// are fetched by the readers the auth server owns (CFG-203).
/// </para>
/// <para>
/// Each declaration goes into <see cref="Catalog"/>, and the ONE registrar of the deployment
/// (<c>PathConfigKeyRegistrar</c>) both declares the key and binds every level of it: what a key is
/// called, where it lives on each level and how it is read is stated once, here.
/// </para>
/// <para>
/// The canonical key NAMES are unchanged by the move: they are the contract an operator reads in the
/// startup map, and they name the section the value comes from, not the assembly that declares them.
/// </para>
/// </summary>
public static class CorePageBrandingConfigKeys
{
    /// <summary>
    /// Catalog of the design keys declared in this assembly. It is filled by the initializers below
    /// and read afterwards by the registrar of the deployment.
    /// </summary>
    private static readonly ConfigKeyCatalog Declared = new();

    /// <summary>
    /// Section of the application configuration the CORE level of the page design lives in
    /// (self-hosted ≡ core, SPEC-012 §10.1). The auth server names the same section through
    /// <c>AuthPageDesignOptions.SectionName</c>, which takes its value from here — the section is one,
    /// and a second literal of it in the other assembly would be a second answer able to drift.
    /// </summary>
    public const string CoreSectionName = "Veriqa:AuthPageDesign";

    /// <summary>
    /// Name of the dimension that cuts the presentational values of a page by theme. Its values are
    /// the theme names of the contour (<see cref="CorePageThemes"/>), and <c>auto</c> is not among
    /// them: with it the browser picks the theme and the server does not know the answer, which is why
    /// such a key is resolved for both themes rather than for one.
    /// </summary>
    public const string ThemeDimensionName = "theme";

    /// <summary>
    /// Design preset the product ships with — the value the core level states where the section states
    /// none. <c>AuthPageDesignOptions.Preset</c> takes its default from here.
    /// <para>
    /// It is stated at the KEY and not taken off the options class, the way the shipped values of the
    /// sign-in window keys are: that class lives in the assembly which references this one, so the
    /// dependency only runs the one way. It is the same arrangement <c>LoggingConfigKeys</c> already
    /// buys for its axis, and it keeps the shipped value in ONE place all the same — a second literal
    /// of it in the options class would be a second answer able to drift.
    /// </para>
    /// </summary>
    public const DesignPreset DefaultPreset = DesignPreset.Default;

    /// <summary>
    /// Design preset of a generated page (SPEC-012 §4.2). Value semantics per FIELD: the record
    /// overrides the preset alone and the remaining design fields keep coming from the global section,
    /// which is what makes a partial <c>ui_config</c> record a partial override rather than a whole
    /// new design.
    /// <para>
    /// The <c>ui_config</c> record spells the value as a JSON string and the global section as
    /// configuration text; either way it reaches the enum through the converter of the platform, and a
    /// value this version does not know leaves the step of the chain unset (CFG-240) instead of
    /// failing the page.
    /// </para>
    /// <para>
    /// The core level DECLARES the shipped preset (<see cref="DefaultPreset"/>) rather than leaving a
    /// deployment that wrote no section unanswered: the value the page is rendered with was that one
    /// either way — the consumer received the default of the TYPE where no level spoke — and declaring
    /// it is what makes the schema of the deployment print the answer instead of "none declared".
    /// </para>
    /// </summary>
    public static ConfigKey<DesignPreset> Preset { get; } = Declared
        .Of<DesignPreset>("AuthPageDesign.Preset")
        .At(ConfigLevel.Core, CoreSectionName + ":Preset")
        .At(ConfigLevel.UiConfig, "preset")
        .Cached(ConfigCachePolicy.ExternalStore)
        .Default(DefaultPreset)
        .Declare();

    /// <summary>
    /// Primary brand color of a generated page (Branded preset), owned by the tenant and overridable
    /// by the application and by the <c>ui_config</c> record (SPEC-012 §9). Cut by theme: a brand that
    /// reads on a light page may be unreadable on a dark one — and the two steps of that cut read
    /// DIFFERENT members of a level (the themed map against the plain field), which is why the key
    /// states a parse hook instead of a second address.
    /// </summary>
    public static ConfigKey<string?> PrimaryColor { get; } = Declared
        .Text("AuthPageDesign.PrimaryColor")
        .Narrowing(ThemeDimensionName)
        .At(ConfigLevel.Core, CoreSectionName + ":PrimaryColor")
        .At(ConfigLevel.Application, "PrimaryColor")
        .At(ConfigLevel.UiConfig, "primary_color")
        .Cached(ConfigCachePolicy.ExternalStore)
        .Parse(static (node, path, point) => CorePageDesignNode.ThemedText(
            node,
            path,
            point,
            "PrimaryColorByTheme",
            "primary_color_by_theme"))

        // A walk reads the plain member the address names and knows nothing of the themed map beside
        // it, so it cannot reproduce what this key resolves to. The report names the pair instead of
        // reporting a value that is only half of what the level states.
        .NotWalked()
        .Declare();

    /// <summary>
    /// Custom stylesheet of a generated page — path AND its SRI hash as ONE value
    /// (<see cref="CorePageCustomResource"/>), so both always come from one level (SPEC-012 §4.3).
    /// Owned by the tenant, overridable by the application and by the <c>ui_config</c> record: a
    /// stylesheet is a presentational asset and carries no executable code. One value over a PAIR of
    /// members is the second shape an address cannot name, hence the parse hook.
    /// <para>
    /// The WALK of a configuration snapshot does not read this pair, and the key SAYS so
    /// (<c>ConfigKeyBuilder.NotWalked</c>): the value stands over TWO members of the record — the path
    /// and its SRI hash — which only the parse hook assembles, and a hook belongs to the path of
    /// reading that calls it. The report of the snapshot therefore NAMES the pairs of this key as
    /// standing outside it, rather than leaving an operator to tell "nothing is stated here" from
    /// "nothing was ever read here".
    /// </para>
    /// </summary>
    public static ConfigKey<CorePageCustomResource?> CustomCss { get; } = Declared
        .Of<CorePageCustomResource?>("AuthPageDesign.CustomCss")
        .At(ConfigLevel.Core, CoreSectionName + ":CustomCssPath")
        .At(ConfigLevel.Application, "CustomCssPath")
        .At(ConfigLevel.UiConfig, "custom_css_path")
        .Cached(ConfigCachePolicy.ExternalStore)
        .Parse(static (node, path, _) => CorePageDesignNode.CustomResource(
            node,
            path,
            "CssSriHash",
            "css_sri_hash"))
        .NotWalked()
        .Declare();

    /// <summary>
    /// Declarations of the branding keys — what the registrar of the deployment declares and binds.
    /// </summary>
    public static ConfigKeyCatalog Catalog => Declared;
}
