// Copyright (c) Dmitrii Erusov
// SPDX-License-Identifier: MPL-2.0

namespace Veriqa.Core.ChannelAdapter.UI;

/// <summary>
/// Theme names of the pages generated by the core (SPEC-015 §2.2). The very same strings play three
/// roles — the values of the <c>data-theme</c> attribute, the theme selectors of the generated token
/// blocks and the values of the <c>theme</c> dimension of the presentational settings — so they live
/// in one holder rather than as literals spread over the renderers.
/// <para>
/// <see cref="Auto"/> is a page MODE and never a value of the dimension: with it the browser picks
/// the theme through <c>prefers-color-scheme</c> and the server does not know the answer, which is
/// why a themed setting is resolved for <see cref="Light"/> and <see cref="Dark"/> both.
/// </para>
/// </summary>
public static class CorePageThemes
{
    /// <summary>
    /// Light theme.
    /// </summary>
    public const string Light = "light";

    /// <summary>
    /// Dark theme.
    /// </summary>
    public const string Dark = "dark";

    /// <summary>
    /// The page follows the browser setting (<c>prefers-color-scheme</c>).
    /// </summary>
    public const string Auto = "auto";

    /// <summary>
    /// Values the <c>theme</c> dimension can be asked about — the themes a page is actually painted
    /// in. <see cref="Auto"/> is deliberately absent: it is a page MODE, and a setting cut by theme is
    /// resolved for both real themes precisely because the server does not know which of them the
    /// browser will pick.
    /// </summary>
    public static IReadOnlyList<string> Painted { get; } = [Light, Dark];
}
