// Copyright (c) Dmitrii Erusov
// SPDX-License-Identifier: MPL-2.0

using Veriqa.Core.Configuration;

namespace Veriqa.Core.ChannelAdapter.UI;

/// <summary>
/// Reading of a sign-in page design value out of the node of ONE level, for the two shapes an address
/// alone cannot name (SPEC-012 §10.6): a value standing over a PAIR of members — a path together with
/// its SRI hash — and a step of a dimensioned chain reading a different member than its neighbour —
/// the map <c>…ByTheme</c> against the plain field.
/// <para>
/// Both are the parse hook of a key, and a hook is ONE per key while the member names differ per
/// record: the levels served by the application configuration spell their members the way the options
/// classes do, and the <c>ui_config</c> record spells them in the snake_case of its JSON contract.
/// Naming both conventions in one place is what keeps the hooks from carrying a copy of that answer
/// apiece.
/// </para>
/// <para>
/// It lives in the channel contour because the design of a page generated by the core has ONE owner
/// spread over two assemblies — the branding keys here, the sign-in window keys in the auth server —
/// and both halves read the same records (see <see cref="CorePageBrandingConfigKeys"/>).
/// </para>
/// </summary>
public static class CorePageDesignNode
{
    /// <summary>
    /// Dimensions a themed map of a level is cut by, innermost last — a single one, the theme. It is
    /// the shape of the level's MAP and never the order of the chain's steps, which the key declares
    /// (see <see cref="DimensionedConfigValue"/>).
    /// </summary>
    private static readonly IReadOnlyList<string> ThemeDimensions =
        [CorePageBrandingConfigKeys.ThemeDimensionName];

    /// <summary>
    /// Layer value of one step of a THEME-cut text setting: the step that addresses the theme answers
    /// from the level's themed map, the step that addresses none from the plain member the key's
    /// address names. A step that states nothing yields <see cref="LayerValue{T}.None"/> and the chain
    /// moves on to its next step.
    /// </summary>
    /// <param name="node">Subtree of the level's record.</param>
    /// <param name="path">Address the step resolved to — the plain member.</param>
    /// <param name="point">Point of the chain handed in by the resolver.</param>
    /// <param name="mapMember">Themed map as the configuration sections spell it.</param>
    /// <param name="mapRecordMember">Themed map as the <c>ui_config</c> record spells it.</param>
    /// <returns>Layer value of the step.</returns>
    public static LayerValue<string?> ThemedText(
        ConfigNode node,
        string path,
        ConfigDimensionValues point,
        string mapMember,
        string mapRecordMember)
    {
        var byTheme = node.TryRead<Dictionary<string, string>>(
            SiblingAddress(node, path, mapMember, mapRecordMember),
            out var map)
            ? map
            : null;

        return DimensionedConfigValue.Layer(point, ThemeDimensions, byTheme, Text(node, path));
    }

    /// <summary>
    /// Layer value of a custom resource stated by a level as the PAIR "path + SRI hash": the hash
    /// belongs to the file the path names, so the two never travel apart (SPEC-012 §4.3). A level that
    /// states no path leaves the level unset and the pair comes whole from the level below.
    /// </summary>
    /// <param name="node">Subtree of the level's record.</param>
    /// <param name="path">Address the step resolved to — the member carrying the resource path.</param>
    /// <param name="hashMember">SRI hash member as the configuration sections spell it.</param>
    /// <param name="hashRecordMember">SRI hash member as the <c>ui_config</c> record spells it.</param>
    /// <returns>Layer value of the level.</returns>
    public static LayerValue<CorePageCustomResource?> CustomResource(
        ConfigNode node,
        string path,
        string hashMember,
        string hashRecordMember) =>
        CorePageCustomResource.LayerOf(
            Text(node, path),
            Text(node, SiblingAddress(node, path, hashMember, hashRecordMember)));

    /// <summary>
    /// Address of a member standing NEXT TO the one the key's address names, inside the same record:
    /// the last segment of the address is replaced with the member asked for. Which spelling of that
    /// member is taken is decided by the level — the <c>ui_config</c> record is a JSON contract with
    /// its own snake_case names, every other record of the design is a configuration section spelled
    /// the way its options class is.
    /// </summary>
    /// <param name="node">Subtree of the level's record.</param>
    /// <param name="path">Address the step resolved to.</param>
    /// <param name="member">Member as the configuration sections spell it.</param>
    /// <param name="recordMember">Member as the <c>ui_config</c> record spells it.</param>
    /// <returns>Address of the neighbouring member.</returns>
    public static string SiblingAddress(ConfigNode node, string path, string member, string recordMember)
    {
        ArgumentNullException.ThrowIfNull(node);
        ArgumentException.ThrowIfNullOrWhiteSpace(path);

        var sibling = node.Level is ConfigLevel.UiConfig ? recordMember : member;
        var separator = path.LastIndexOf(ConfigNode.PathSeparator);

        return separator < 0 ? sibling : string.Concat(path.AsSpan(0, separator + 1), sibling);
    }

    /// <summary>
    /// Text a level states at an address, or null when it states nothing there.
    /// </summary>
    /// <param name="node">Subtree of the level's record.</param>
    /// <param name="path">Address inside the record.</param>
    /// <returns>Text stated, or null.</returns>
    private static string? Text(ConfigNode node, string path)
    {
        ArgumentNullException.ThrowIfNull(node);

        return node.TryRead<string>(path, out var value) ? value : null;
    }
}
