// Copyright (c) Dmitrii Erusov
// SPDX-License-Identifier: MPL-2.0

namespace Veriqa.Core.ChannelAdapter.UI;

/// <summary>
/// Built-in design preset of the pages generated by the core (SPEC-012 §4.2, CFG-020…CFG-023).
/// The preset defines the color scheme, the set of decorative elements, and the button style.
/// If a custom design is set (CustomCssPath, §4.3), the preset is ignored (CFG-023).
/// </summary>
public enum DesignPreset
{
    /// <summary>
    /// Standard light Veriqa theme.
    /// </summary>
    Default,

    /// <summary>
    /// Dark theme.
    /// </summary>
    Dark,

    /// <summary>
    /// Minimalist design: QR and buttons only, no decorative elements — the sign-in window renders no
    /// brand row.
    /// </summary>
    Minimal,

    /// <summary>
    /// Branded design: honours the client's primary color (PrimaryColor). The client's logo and brand
    /// name are not tied to this preset — the brand row reads them in every preset but Minimal.
    /// </summary>
    Branded
}
